In [72]:
try:
    import numpy as np
    import PIL
    from PIL import Image
    from numpy import asarray
    import time
    import copy
except:
    !pip install Pillow
    !pip install numpy
    import numpy as np
    import PIL
    from PIL import Image
    from numpy import asarray
    import time

In [11]:
bat = 20
m = 480 // bat
n = 720 // bat
m,n

(24, 36)

In [265]:
preg = []
same = False
R=-1
two_over = [False,-1]
for i in range(m):
    preg.append([])
    if list(carray[i]) != [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9]:
        for j in range(n):
            if two_over[0] == True:
                if two_over[1] == j:
                    two_over[0] = False
                else:
                    continue
            if carray[i,j] != 9 and same == False:
                preg[i].append([j,-1])
                R+=1
                same = True
                if j == n-1:
                    preg[i][R] = [i,j]
                elif carray[i,j+1] ==9:
                    preg[i][R] = [j,j]
            elif carray[i,j]!=9:
                preg[i][R] = [preg[i][R][0],j]
            elif j < 34 and carray[i,j+2]!=9:
                two_over = [True, j+2]
            else:
                same = False
            
            print(i,j,preg[i])
        R = -1
        same = False

4 0 []
4 1 []
4 2 []
4 3 []
4 4 []
4 5 []
4 6 []
4 7 []
4 8 []
4 9 []
4 10 []
4 11 []
4 13 [[13, -1]]
4 14 [[13, 14]]
4 15 [[13, 14]]
4 16 [[13, 14]]
4 17 [[13, 14]]
4 18 [[13, 14]]
4 19 [[13, 14]]
4 20 [[13, 14]]
4 21 [[13, 14]]
4 22 [[13, 14]]
4 23 [[13, 14]]
4 24 [[13, 14]]
4 25 [[13, 14]]
4 26 [[13, 14]]
4 27 [[13, 14]]
4 28 [[13, 14]]
4 29 [[13, 14]]
4 30 [[13, 14]]
4 31 [[13, 14]]
4 32 [[13, 14]]
4 33 [[13, 14]]
4 34 [[13, 14]]
4 35 [[13, 14]]
5 0 []
5 1 []
5 2 []
5 3 []
5 4 []
5 5 []
5 6 []
5 7 []
5 8 []
5 9 []
5 10 []
5 12 [[12, -1]]
5 13 [[12, 13]]
5 14 [[12, 14]]
5 15 [[12, 14]]
5 16 [[12, 14]]
5 17 [[12, 14]]
5 18 [[12, 14]]
5 19 [[12, 14]]
5 20 [[12, 14]]
5 21 [[12, 14]]
5 22 [[12, 14]]
5 23 [[12, 14]]
5 24 [[12, 14]]
5 25 [[12, 14]]
5 26 [[12, 14]]
5 27 [[12, 14]]
5 28 [[12, 14]]
5 29 [[12, 14]]
5 30 [[12, 14]]
5 31 [[12, 14]]
5 32 [[12, 14]]
5 33 [[12, 14]]
5 35 [[12, 14], [5, 35]]
6 0 []
6 1 []
6 2 []
6 3 []
6 4 []
6 5 []
6 6 []
6 7 []
6 9 [[9, -1]]
6 10 [[9, -1]]
6 11 [

22 27 [[0, 14], [18, 26]]
22 28 [[0, 14], [18, 26]]
22 30 [[0, 14], [18, 26], [30, -1]]
22 31 [[0, 14], [18, 26], [30, 31]]
22 32 [[0, 14], [18, 26], [30, 32]]
22 33 [[0, 14], [18, 26], [30, 32]]
22 34 [[0, 14], [18, 26], [30, 32]]
22 35 [[0, 14], [18, 26], [30, 32]]
23 0 [[0, -1]]
23 1 [[0, 1]]
23 2 [[0, 2]]
23 3 [[0, 3]]
23 4 [[0, 4]]
23 5 [[0, 5]]
23 6 [[0, 6]]
23 7 [[0, 7]]
23 8 [[0, 8]]
23 9 [[0, 9]]
23 10 [[0, 10]]
23 11 [[0, 11]]
23 12 [[0, 12]]
23 13 [[0, 12]]
23 14 [[0, 12], [14, -1]]
23 15 [[0, 12], [14, -1]]
23 16 [[0, 12], [14, -1]]
23 17 [[0, 12], [14, -1]]
23 18 [[0, 12], [14, -1]]
23 19 [[0, 12], [14, -1]]
23 20 [[0, 12], [14, -1]]
23 21 [[0, 12], [14, -1]]
23 23 [[0, 12], [14, -1], [23, -1]]
23 24 [[0, 12], [14, -1], [23, 24]]
23 25 [[0, 12], [14, -1], [23, 25]]
23 26 [[0, 12], [14, -1], [23, 26]]
23 27 [[0, 12], [14, -1], [23, 26]]
23 28 [[0, 12], [14, -1], [23, 26], [28, -1]]
23 29 [[0, 12], [14, -1], [23, 26], [28, -1]]
23 30 [[0, 12], [14, -1], [23, 26], [28, -1]]
2

In [267]:
for i in range(len(preg)):
    print(preg[i])
n,m

[]
[]
[]
[]
[[13, 14]]
[[12, 14], [5, 35]]
[[9, -1], [13, 15], [28, 35]]
[[10, 16], [32, 35]]
[[10, 17], [29, -1], [34, 35]]
[[13, 18], [34, 35]]
[[12, 25]]
[[12, 28], [33, 35]]
[[12, 25]]
[[0, 1], [13, 29]]
[[15, 29]]
[[15, 27], [29, -1]]
[[15, 20], [24, 27], [29, 32]]
[[0, 7], [24, 25], [29, 34]]
[[0, 5], [23, 25], [29, 32]]
[[0, 3], [24, 30]]
[[0, 9], [23, 33]]
[[0, 2], [4, 7], [20, 29], [31, -1]]
[[0, 14], [18, 26], [30, 32]]
[[0, 12], [14, -1], [23, 26], [28, -1]]


(36, 24)

In [242]:
sagment = []
asa = True
for i in range(m):
    if preg[i] != []:
        sag = copy.deepcopy(sagment)
        for pn in range(len(preg[i])):
            for sn in range(len(sag)):
                #print(pn,sn,i, preg[i], sag)
                #print(preg[i][pn],sag[sn][-1]) # set(preg[i][pn]) & set(sag[sn][-1]) != set():
                if sag[sn][-1] != [] and (sag[sn][-1][0] <= preg[i][pn][1] and sag[sn][-1][1] >= preg[i][pn][0]):
                    if len(sagment[sn]) == i:
                        sagment[sn].append(preg[i][pn]+[i])
                    else:
                        print(preg[i][pn], type(preg[i][pn]))
                        sagment.append(sagment[sn][0:-1]+[preg[i][pn]+[i]])
                    asa = False
                elif sag[sn][-1] != [] and (sag[sn][-1][0] <= preg[i][pn+1][1] and sag[sn][-1][1] >= preg[i][pn+1][0]):
                    if len(sagment[sn]) == i:
                        sagment[sn].append(sag[sn][-1])
                    else:
                        print(preg[i][pn], type(preg[i][pn]))
                        sagment.append(sagment[sn][0:-1]+[sag[sn][-1]])
                #else:
                #    sag[sn].append([])
            if asa == True:
                sagment.append([])
                for asdf in range(i):
                    sagment[-1].append([])
                sagment[-1].append(preg[i][pn]+[i])
            asa = True
        for sn in range(len(sagment)):
            if len(sagment[sn]) != i+1:
                sagment[sn].append([])
            print(len(sagment[sn]),sagment[sn], end = " ")
        print("")
        print("")

5 [[], [], [], [], [13, 14, 4]] 

6 [[], [], [], [], [13, 14, 4], [12, 14, 5]] 6 [[], [], [], [], [], [35, 35, 5]] 

7 [[], [], [], [], [13, 14, 4], [12, 14, 5], [13, 15, 6]] 7 [[], [], [], [], [], [35, 35, 5], [28, 35, 6]] 7 [[], [], [], [], [], [], [9, 9, 6]] 

8 [[], [], [], [], [13, 14, 4], [12, 14, 5], [13, 15, 6], [10, 16, 7]] 8 [[], [], [], [], [], [35, 35, 5], [28, 35, 6], [32, 35, 7]] 8 [[], [], [], [], [], [], [9, 9, 6], []] 

9 [[], [], [], [], [13, 14, 4], [12, 14, 5], [13, 15, 6], [10, 16, 7], [10, 17, 8]] 9 [[], [], [], [], [], [35, 35, 5], [28, 35, 6], [32, 35, 7], [34, 35, 8]] 9 [[], [], [], [], [], [], [9, 9, 6], [], []] 9 [[], [], [], [], [], [], [], [], [29, 29, 8]] 

10 [[], [], [], [], [13, 14, 4], [12, 14, 5], [13, 15, 6], [10, 16, 7], [10, 17, 8], [13, 18, 9]] 10 [[], [], [], [], [], [35, 35, 5], [28, 35, 6], [32, 35, 7], [34, 35, 8], [34, 35, 9]] 10 [[], [], [], [], [], [], [9, 9, 6], [], [], []] 10 [[], [], [], [], [], [], [], [], [29, 29, 8], []] 

11 [[], [],

In [243]:
for i in range(len(sagment)):
    print((sagment[i]))

[[], [], [], [], [13, 14, 4], [12, 14, 5], [13, 15, 6], [10, 16, 7], [10, 17, 8], [13, 18, 9], [12, 25, 10], [12, 28, 11], [12, 25, 12], [13, 29, 13], [15, 29, 14], [15, 27, 15], [15, 20, 16], [], [], [], [], [], [], []]
[[], [], [], [], [], [35, 35, 5], [28, 35, 6], [32, 35, 7], [34, 35, 8], [34, 35, 9], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
[[], [], [], [], [], [], [9, 9, 6], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
[[], [], [], [], [], [], [], [], [29, 29, 8], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
[[], [], [], [], [], [], [], [], [], [], [], [33, 35, 11], [], [], [], [], [], [], [], [], [], [], [], []]
[[], [], [], [], [], [], [], [], [], [], [], [], [], [0, 1, 13], [], [], [], [], [], [], [], [], [], []]
[[], [], [], [], [13, 14, 4], [12, 14, 5], [13, 15, 6], [10, 16, 7], [10, 17, 8], [13, 18, 9], [12, 25, 10], [12, 28, 11], [12, 25, 12], [13, 29, 13], [15, 29, 14], [29, 29, 15], [29, 32, 16], [29, 34, 17], [29, 32,

In [244]:
for i in range(len(sagment)):
    sagment[i] = list(map(tuple, sagment[i]))
    
div = [set(sagment[0])]
del sagment[0]


while True:
    im = sagment[0]
    for i in range(len(div)):
        print(div[i] & set(sagment[0]),(div[i] & set(sagment[0])) != set([()]))
        a = div[i] & set(sagment[0])
        if a != {()}:
            div[i] = div[i] | set(sagment[0])
            del sagment[0]
            print("?")
        print("!")
    if sagment != [] and im == sagment[0]:
        print("!!")
        div.append(set(sagment[0]))
        del sagment[0]
                    
    if sagment == []:
        break

{()} False
!
!!
{()} False
!
{()} False
!
!!
{()} False
!
{()} False
!
{()} False
!
!!
{()} False
!
{()} False
!
{()} False
!
{()} False
!
!!
{()} False
!
{()} False
!
{()} False
!
{()} False
!
{()} False
!
!!
{(13, 15, 6), (10, 17, 8), (13, 18, 9), (12, 25, 10), (12, 14, 5), (13, 14, 4), (10, 16, 7), (12, 28, 11), (15, 29, 14), (), (13, 29, 13), (12, 25, 12)} True
?
!
{()} False
!
{()} False
!
{()} False
!
{()} False
!
{()} False
!
{(15, 27, 15), (13, 15, 6), (10, 17, 8), (24, 30, 19), (12, 25, 10), (13, 18, 9), (23, 26, 23), (12, 14, 5), (13, 14, 4), (10, 16, 7), (15, 29, 14), (12, 28, 11), (), (18, 26, 22), (13, 29, 13), (12, 25, 12), (23, 33, 20), (20, 29, 21)} True
?
!
{()} False
!
{()} False
!
{()} False
!
{()} False
!
{()} False
!
{()} False
!
{()} False
!
{()} False
!
{()} False
!
{()} False
!
{()} False
!
!!
{()} False
!
{()} False
!
{()} False
!
{()} False
!
{()} False
!
{()} False
!
{(0, 14, 22), (0, 12, 23), (0, 9, 20), (0, 3, 19), (), (0, 5, 18), (0, 7, 17)} True
?
!
{(13,

In [245]:
for i in range(len(div)):
    print(div[i])

{(15, 20, 16), (10, 17, 8), (24, 30, 19), (24, 27, 16), (23, 25, 18), (12, 14, 5), (10, 16, 7), (15, 29, 14), (13, 29, 13), (12, 25, 12), (15, 27, 15), (31, 31, 21), (29, 34, 17), (13, 14, 4), (29, 29, 15), (23, 33, 20), (20, 29, 21), (13, 15, 6), (24, 25, 17), (12, 25, 10), (13, 18, 9), (29, 32, 18), (23, 26, 23), (12, 28, 11), (), (29, 32, 16), (18, 26, 22), (30, 32, 22)}
{(34, 35, 9), (35, 35, 5), (), (28, 35, 6), (32, 35, 7), (34, 35, 8)}
{(), (9, 9, 6)}
{(29, 29, 8), ()}
{(), (33, 35, 11)}
{(), (0, 1, 13)}
{(0, 2, 21), (0, 14, 22), (14, 14, 23), (0, 9, 20), (0, 12, 23), (0, 3, 19), (), (0, 5, 18), (4, 7, 21), (0, 7, 17)}
{(28, 28, 23), ()}


In [246]:
past = len(div)
now = -1
while past != now:
    for i in range(1, len(div)):
        if i<len(div) and div[0]&div[i] != {()}:
            div[0] = div[0] | div[i]
    if len(div) == 1:
        break
    div = div[1:] + [div[0]]
    now = len(div)

In [247]:
divv = copy.deepcopy(div)
for i in range(len(div)):
    div[i] = list(map(list, div[i]))

In [248]:
res = []
for i in range(len(div)-1,-1,-1):
    if i <= len(div) and len(div[i]) > 4:
        div[i].remove([])
        im = np.asarray(div[i]).T
        print(im)
        res.append([np.min(im[0]),np.max(im[1]), np.max(im[2]),np.min(im[2])]) # 좌우하상

[[15 10 24 24 23 12 10 15 13 12 15 31 29 13 29 23 20 13 24 12 13 29 23 12
  29 18 30]
 [20 17 30 27 25 14 16 29 29 25 27 31 34 14 29 33 29 15 25 25 18 32 26 28
  32 26 32]
 [16  8 19 16 18  5  7 14 13 12 15 21 17  4 15 20 21  6 17 10  9 18 23 11
  16 22 22]]
[[ 0  0 14  0  0  0  0  4  0]
 [ 2 14 14  9 12  3  5  7  7]
 [21 22 23 20 23 19 18 21 17]]
[[34 35 28 32 34]
 [35 35 35 35 35]
 [ 9  5  6  7  8]]


In [252]:
res

[[10, 34, 23, 4], [0, 14, 23, 17], [28, 35, 9, 5]]

In [264]:
num = 'image'
#print(num,'.jpg')
image = Image.open('{}.jpg'.format(num))
image = image.resize((720, 480))

area = (res[0][0]*bat, res[0][3]*bat, res[0][1]*bat, res[0][2]*bat)
print(area)
cropped_img = image.crop(area)
cropped_img.show()

(200, 80, 680, 460)


In [262]:
num = 'image'
#print(num,'.jpg')
image = Image.open('{}.jpg'.format(num))
image = image.resize((720, 480))

area = (200,80,680,460)
cropped_img = image.crop(area)
cropped_img.show()

In [ ]:
(200, 460, 680, 80)